// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateExampleJSON() {
  return window['go']['main']['App']['CreateExampleJSON']();
}

export function GetJSONFromFile(arg1) {
  return window['go']['main']['App']['GetJSONFromFile'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
